### PR TITLE
added support for Maestro files input (Using Schrodinger libraries); …

### PR DESCRIPTION
**Pull request by dimkal**
…refactored code by modularizing reading coordinates.

### CODE REVIEW

**Comment by jgreener64** [comment]
Looks like a good change, thanks.

Could you revert the changes of variable names to capitals and the changes of `return` to `sys.exit` though? The first is just a preference, the second so that people can use the `view` function in their scripts and return back to their control flow on exiting.

**Comment by dimkal** [comment]
good point. I've removed the `sys.exit(1)` calls from the main function. Regarding the capital names, do you mean the variables like `ZOOM_SPEED`?

**Comment by jgreener64** [comment]
> good point. I've removed the `sys.exit(1)` calls from the main function

Thanks.

> do you mean the variables like `ZOOM_SPEED`

Yes.

**Comment by dimkal** [comment]
okay done. I've kept the capital variable names for all the constant variables.

**Comment by dimkal** [comment]
anything else to do here?

**Pull request merged**
